In [3]:
import numpy as np
print(np.__version__)

1.18.1


In [5]:
x = np.array([4,5,6])
x

array([4, 5, 6])

In [6]:
x.dtype

dtype('int32')

In [7]:
y = np.array([3.4,9.1,11.2])
y.dtype

dtype('float64')

In [9]:
t = np.array([(1,2),(3,4),(5,6)])
t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
f = np.array([(9,8,7),(6,5,4)], dtype=complex)
f

array([[9.+0.j, 8.+0.j, 7.+0.j],
       [6.+0.j, 5.+0.j, 4.+0.j]])

In [16]:
l = np.arange(25)
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
np.full((5, 5), True, dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [34]:
array1 = np.array([0,1,2,3,4,6,7,8,9])

In [40]:
array1[array1 % 2 == 1]

array([1, 3, 7, 9])

In [44]:
xt = np.arange(9)
print (xt)

[0 1 2 3 4 5 6 7 8]


In [48]:
xu = np.arange(12).reshape(3,4)
print (xu)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
xv = np.arange(36).reshape(3,3,4)
print (xv)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [110]:
#replacing value with -1
array2 = np.array([0,1,2,3,4,5,6,7,8,9])
array2[array2 %2 == 1 ] = -1
print(array2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [207]:
xz = np.arange(24).reshape(2,2,6)
print(xz)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


In [209]:
xy = np.arange(48).reshape(3,4,4)
print(xy)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [219]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [220]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [224]:
c = a-b
c

array([20, 29, 38, 47])

In [223]:
d = b-a
d

array([-20, -29, -38, -47])

In [73]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [74]:
15*np.cos(a)

array([-11.39531869,   6.12123093,  14.86804218,   2.31377175])

In [75]:
10*np.sin(a)

array([ 6.5028784 ,  9.12945251, -1.3235175 , -9.88031624])

In [76]:
4*np.tan(a)

array([ -3.4239736 ,   8.94864378,  -0.53410563, -25.62132479])

In [77]:
a>21

array([False, False,  True,  True])

In [78]:
c = np.array([[1,0],
              [0,1]])
d = np.array([[3,4],
              [5,6]])

In [90]:
#elements product
c*d

array([[3, 0],
       [0, 6]])

In [91]:
#matrix product
c@d

array([[3, 4],
       [5, 6]])

In [92]:
#matrix product method 2
c.dot(d)

array([[3, 4],
       [5, 6]])

In [211]:
yu = np.array([15,20,25,30])
yv = np.arange(4)
print(yu)
print(yv)

[15 20 25 30]
[0 1 2 3]


In [226]:
m = np.arange(10).reshape(2,-1)

In [227]:
n = np.repeat(1,10).reshape(2,-1)

In [229]:
print(m)
print(n)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [230]:
#concatenating 2 matrix method 1
np.concatenate([m, n], axis=1)

array([[0, 1, 2, ..., 1, 1, 1],
       [5, 6, 7, ..., 1, 1, 1]])

In [231]:
#concatenating 2 matrix method 2
np.hstack([m,n])

array([[0, 1, 2, ..., 1, 1, 1],
       [5, 6, 7, ..., 1, 1, 1]])

In [232]:
#concatenating 2 matrix method 3
np.c_[m,n]

array([[0, 1, 2, ..., 1, 1, 1],
       [5, 6, 7, ..., 1, 1, 1]])

In [112]:
array2 = np.array([11,22,33])

In [116]:
np.r_[np.repeat(array2,3),np.tile(array2,3)]

array([11, 11, 11, 22, 22, 22, 33, 33, 33, 11, 22, 33, 11, 22, 33, 11, 22,
       33])

In [123]:
array3 = np.array([31,32,33,32,33,34,33,34,35,36])
array4 = np.array([17,21,10,32,27,14,33,14,29,18])

In [126]:
np.intersect1d(array3,array4)

array([32, 33])

In [131]:
array11 = np.array([1,2,3,4,5,6,7,8,9])
array12 = np.array([1,3,11,15,19])

In [132]:
np.setdiff1d(array11,array12)

array([2, 4, 5, 6, 7, 8, 9])

In [133]:
np.setdiff1d(array12,array11)

array([11, 15, 19])

In [147]:
e = np.array([1,2,3,2,3,4,3,4,5,6])
p = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(p == e)

(array([1, 3, 5, 7], dtype=int64),)

In [191]:
#making matrix with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [192]:
#making matrix with ones
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       ...,
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [190]:
#placing random values
np.empty((3,2))

array([[2.1220e-314, 6.3660e-314],
       [1.0610e-313, 1.4854e-313],
       [1.9098e-313, 2.3342e-313]])

In [160]:
ink = np.arange(9).reshape(3,3)
ink

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
#swapping column
ink [:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [165]:
#swapping row
ink [[2,0,1] ,:]

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [169]:
#reverse row
ink[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [172]:
#reverse columns
ink[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [176]:
#generating random numbers between 5 to 10
array21 = np.arange(12).reshape(3,4)
rand_array21 = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print (rand_array21)

[[8.27083287 7.39139042 6.55666622]
 [5.77124652 6.40632752 7.32898701]
 [5.88149653 9.51204314 9.96526788]
 [5.85027129 8.17002991 9.28127989]
 [5.65434384 8.51332445 6.92979414]]


In [181]:
# Limiting number to 4 decimal places
rand_array22 = np.random.random([5,3])

np.set_printoptions(precision=4)
rand_array22[:4]

array([[0.5733, 0.6784, 0.6768],
       [0.8134, 0.124 , 0.6155],
       [0.7829, 0.6643, 0.7667],
       [0.6582, 0.0478, 0.5575]])

In [183]:
#printing/displaying limited values; here 6 values only
array31 = np.arange(25)
np.set_printoptions(threshold=6)
array31

array([ 0,  1,  2, ..., 22, 23, 24])

In [193]:
array34 = np.arange(16).reshape(4,4)
array34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [195]:
#sum of column values
array34.sum(axis=0)

array([24, 28, 32, 36])

In [196]:
#sum of rows values
array34.sum(axis=1)

array([ 6, 22, 38, 54])

In [197]:
#minimum of columns
array34.min(axis=0)

array([0, 1, 2, 3])

In [198]:
#minimum of rows
array34.min(axis=1)

array([ 0,  4,  8, 12])

In [200]:
#cumulative sum along each row
array34.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]], dtype=int32)

In [201]:
#cumulative sum along each column
array34.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)